#!/usr/bin/env bash
set -euo pipefail

output="$CHECKOUT_DIR/.codeboarding"
mkdir -p "$output"

# New Core releases expose one canonical manifest. The compatibility imports
# keep the currently pinned 0.13.7 release usable without duplicating filenames.
manifest="$(python3 - <<'PY'
try:
    from constants import ANALYSIS_FILENAME, PERSISTED_ANALYSIS_ARTIFACT_FILENAMES as artifacts
except ImportError:
    from static_analyzer.analysis_cache import STATIC_ANALYSIS_PKL, STATIC_ANALYSIS_SHA
    from utils import ANALYSIS_FILENAME, FINGERPRINT_FILENAME
    artifacts = (ANALYSIS_FILENAME, FINGERPRINT_FILENAME, STATIC_ANALYSIS_PKL, STATIC_ANALYSIS_SHA, "codeboarding_version.json")
print(ANALYSIS_FILENAME)
print(*artifacts, sep="\n")
PY
)" || { echo "::error::Could not read Core's persisted artifact manifest."; exit 1; }
[ -n "$manifest" ] || { echo "::error::Core's persisted artifact manifest is empty."; exit 1; }
mapfile -t manifest_entries <<< "$manifest"
required="${manifest_entries[0]}"
artifacts=("${manifest_entries[@]:1}")
[ -f "$ANALYSIS_DIR/$required" ] || { echo "::error::Core did not produce $required."; exit 1; }

installed=0
for name in "${artifacts[@]}"; do
  source="$ANALYSIS_DIR/$name"
  target="$output/$name"
  if [ -f "$source" ]; then
    cp "$source" "$target"
    installed=$((installed + 1))
  elif [ -e "$target" ]; then
    rm -f "$target"
  fi
  printf '%s\n' "$target"
done

# Remove documentation generated by v1. User-owned configuration in the same
# directory is deliberately untouched.
for legacy in "$output"/*.md "$output/health/health_report.json" \
  "$CHECKOUT_DIR/docs/development/architecture.md"; do
  [ -e "$legacy" ] || continue
  rm -f "$legacy"
  printf '%s\n' "$legacy"
done

echo "installed=$installed" >> "$GITHUB_OUTPUT"
